/* 
 * MX API
 *
 * The MX Atrium API supports over 48,000 data connections to thousands of financial institutions. It provides secure access to your users' accounts and transactions with industry-leading cleansing, categorization, and classification.  Atrium is designed according to resource-oriented REST architecture and responds with JSON bodies and HTTP response codes.  Use Atrium's development environment, vestibule.mx.com, to quickly get up and running. The development environment limits are 100 users, 25 members per user, and access to the top 15 institutions. Contact MX to purchase production access. 
 *
 * OpenAPI spec version: 0.1
 * 
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using atrium-csharp.Api;
using atrium-csharp.Model;
using atrium-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace atrium-csharp.Test
{
    /// <summary>
    ///  Class for testing TransactionsCleanseAndCategorizeAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionsCleanseAndCategorizeAttributesTests
    {
        // TODO uncomment below to declare an instance variable for TransactionsCleanseAndCategorizeAttributes
        //private TransactionsCleanseAndCategorizeAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionsCleanseAndCategorizeAttributes
            //instance = new TransactionsCleanseAndCategorizeAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionsCleanseAndCategorizeAttributes
        /// </summary>
        [Test]
        public void TransactionsCleanseAndCategorizeAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionsCleanseAndCategorizeAttributes
            //Assert.IsInstanceOfType<TransactionsCleanseAndCategorizeAttributes> (instance, "variable 'instance' is a TransactionsCleanseAndCategorizeAttributes");
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Test]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'IsBillPay'
        /// </summary>
        [Test]
        public void IsBillPayTest()
        {
            // TODO unit test for the property 'IsBillPay'
        }
        /// <summary>
        /// Test the property 'IsDirectDeposit'
        /// </summary>
        [Test]
        public void IsDirectDepositTest()
        {
            // TODO unit test for the property 'IsDirectDeposit'
        }
        /// <summary>
        /// Test the property 'IsExpense'
        /// </summary>
        [Test]
        public void IsExpenseTest()
        {
            // TODO unit test for the property 'IsExpense'
        }
        /// <summary>
        /// Test the property 'IsFee'
        /// </summary>
        [Test]
        public void IsFeeTest()
        {
            // TODO unit test for the property 'IsFee'
        }
        /// <summary>
        /// Test the property 'IsIncome'
        /// </summary>
        [Test]
        public void IsIncomeTest()
        {
            // TODO unit test for the property 'IsIncome'
        }
        /// <summary>
        /// Test the property 'IsInternational'
        /// </summary>
        [Test]
        public void IsInternationalTest()
        {
            // TODO unit test for the property 'IsInternational'
        }
        /// <summary>
        /// Test the property 'IsOverdraftFee'
        /// </summary>
        [Test]
        public void IsOverdraftFeeTest()
        {
            // TODO unit test for the property 'IsOverdraftFee'
        }
        /// <summary>
        /// Test the property 'IsPayrollAdvance'
        /// </summary>
        [Test]
        public void IsPayrollAdvanceTest()
        {
            // TODO unit test for the property 'IsPayrollAdvance'
        }

    }

}
